# Generated by Django 5.0.4 on 2024-04-09 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser_intersting_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='content',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.contentmodel'),
            preserve_default=False,
        ),
    ]
