# Generated by Django 5.0.4 on 2024-04-09 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.contentmodel'),
        ),
    ]
