# Generated by Django 5.0.4 on 2024-04-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customuser_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='content',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='intersting_content',
        ),
        migrations.AddField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('Для Младшего Ребёнка ', 'Для Младшего Ребёнка'), ('Для Себя', 'Для Себя'), ('Для Любого', 'Для Любого')], default=1, max_length=50, verbose_name='выберите для кого вы создаёте этот аккаунт '),
            preserve_default=False,
        ),
    ]
