# Generated by Django 5.0.4 on 2024-04-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_customuser_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='content_type',
            field=models.CharField(blank=True, choices=[('Для Младшего Ребёнка ', 'Для Младшего Ребёнка'), ('Для Себя', 'Для Себя'), ('Для Семьи', 'Для Семьи'), ('Для Всех', 'Для Всех')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('Для Младшего Ребёнка ', 'Для Младшего Ребёнка'), ('Для Себя', 'Для Себя'), ('Для Семьи', 'Для Семьи'), ('Для Всех', 'Для Всех')], max_length=50, verbose_name='выберите для кого вы создаёте этот аккаунт '),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='blog',
            field=models.CharField(choices=[('Личный Блог', 'Личный Блог'), ('Профессиональный Блог', 'Профессиональный Блог')], max_length=80),
        ),
    ]
